In [1]:
import cv2

In [4]:
video=cv2.VideoCapture(0)
Model_face=cv2.CascadeClassifier("trained model/haarcascade_frontalface_alt.xml")
Model_eye=cv2.CascadeClassifier("trained model\haarcascade_eye.xml")
while True:
    flag,img=video.read()  # if img exist then flag value will be True else flag value will be false
    if flag==False:
        break

    img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=Model_face.detectMultiScale(img2)
    cv2.putText(img,text="Press 'c' to stop",org=(10,20),fontFace=cv2.FONT_HERSHEY_COMPLEX,color=(0,0,255),thickness=2,fontScale=1)
    for x,y,w,h in face:
        cv2.rectangle(img,(x,y,w,h),(0,255,0),2)
        

        img3=img2[y:y+h,x:x+w]
        eye=Model_eye.detectMultiScale(img3)
        for ex,ey,ew,eh in eye:
            cv2.rectangle(img,(x+ex,y+ey,ew,eh),(0,255,0),2)

    cv2.imshow("wind",img)
    key=cv2.waitKey(10)
    
    if key==ord("c"):
        break
cv2.destroyAllWindows()
video.release()


In [5]:
vdo=cv2.VideoCapture(0)
Model_face=cv2.CascadeClassifier("trained model\haarcascade_frontalface_alt_tree.xml")
i=1
while True:
    flag,img=vdo.read()
    if flag==False:
        break
    img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=Model_face.detectMultiScale(img2)
    for x,y,w,h in face:
        cv2.rectangle(img,(x,y,w,h),(0,255,0),2)
        slice_face=img2[y:y+h,x:x+w]
        slice_face=cv2.resize(slice_face,(100,100))
        cv2.imwrite(f"images/img{i}.jpg",slice_face)
        i=i+1
    cv2.imshow("wind",img)
    key=cv2.waitKey(20)
    if key==ord("c"):
        break
cv2.destroyAllWindows()
vdo.release()

In [6]:
import cv2
video=cv2.VideoCapture(0)          # video is a collection of images
Model_face=cv2.CascadeClassifier(r"trained model\haarcascade_frontalface_alt.xml")
i=1
while True:
    flag,img=video.read()       # flag -> if img shows then flag true otherwise false
    if flag==False:
        break
    img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=Model_face.detectMultiScale(img2)
    for x,y,w,h in face:
        cv2.rectangle(img,(x,y,w,h),(0,255,0),2)
        slice_face=img2[y:y+h,x:x+w]
        slice_face=cv2.resize(slice_face,(100,100))
        cv2.imwrite(f"Students/Jhanvi/img{i}.jpg",slice_face)
        i=i+1
    cv2.imshow("wind",img)
    key=cv2.waitKey(20)
    if key==ord("c"):
        break
cv2.destroyAllWindows()
video.release()

In [2]:
img=cv2.imread(r"C:\Users\Dell\Desktop\New folder (2)\WD_MachineLearning-23-01-2023-\Face_detection_model\Students\Jhanvi\img1.jpg",0)
cv2.imshow("window",img)
cv2.waitKey()

cv2.destroyAllWindows()

In [3]:
img.ndim

2

In [4]:
print(img)
print(img.shape)

[[ 53  51  48 ...  98 112 115]
 [ 52  49  46 ...  86  98 109]
 [ 50  47  47 ...  81  82  87]
 ...
 [139 136 138 ...  15  16  16]
 [139 131 128 ...  15  15  15]
 [ 96  69  52 ...  15  15  15]]
(100, 100)


In [5]:
img.flatten()

array([53, 51, 48, ..., 15, 15, 15], dtype=uint8)

In [6]:
len(img.flatten())

10000

In [7]:
import glob

address=glob.glob(r"C:\Users\Dell\Desktop\New folder (2)\WD_MachineLearning-23-01-2023-\Face_detection_model\Students\Jhanvi\*.*")
                   #if name of img is not known then put *.*
address

['C:\\Users\\Dell\\Desktop\\New folder (2)\\WD_MachineLearning-23-01-2023-\\Face_detection_model\\Students\\Jhanvi\\img1.jpg',
 'C:\\Users\\Dell\\Desktop\\New folder (2)\\WD_MachineLearning-23-01-2023-\\Face_detection_model\\Students\\Jhanvi\\img10.jpg',
 'C:\\Users\\Dell\\Desktop\\New folder (2)\\WD_MachineLearning-23-01-2023-\\Face_detection_model\\Students\\Jhanvi\\img100.jpg',
 'C:\\Users\\Dell\\Desktop\\New folder (2)\\WD_MachineLearning-23-01-2023-\\Face_detection_model\\Students\\Jhanvi\\img101.jpg',
 'C:\\Users\\Dell\\Desktop\\New folder (2)\\WD_MachineLearning-23-01-2023-\\Face_detection_model\\Students\\Jhanvi\\img102.jpg',
 'C:\\Users\\Dell\\Desktop\\New folder (2)\\WD_MachineLearning-23-01-2023-\\Face_detection_model\\Students\\Jhanvi\\img103.jpg',
 'C:\\Users\\Dell\\Desktop\\New folder (2)\\WD_MachineLearning-23-01-2023-\\Face_detection_model\\Students\\Jhanvi\\img104.jpg',
 'C:\\Users\\Dell\\Desktop\\New folder (2)\\WD_MachineLearning-23-01-2023-\\Face_detection_model\\St

In [8]:
# feature and traget 

X=[]
y=[]

for i in address:
    img=cv2.imread(i,0)
    flattern_img=img.flatten()
    X.append(flattern_img)
    y.append("Jhanvi")

In [1]:
import cv2
vdo=cv2.VideoCapture(0)
Model_face=cv2.CascadeClassifier(r"trained model\haarcascade_frontalface_alt_tree.xml")
i=1
while True:
    flag,img=vdo.read()
    if flag==False:
        break
    img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=Model_face.detectMultiScale(img2)
    for x,y,w,h in face:
        cv2.rectangle(img,(x,y,w,h),(0,255,0),2)
        slice_face=img2[y:y+h,x:x+w]
        slice_face=cv2.resize(slice_face,(100,100))
        cv2.imwrite(f"Students/Dhurv/img{i}.jpg",slice_face)
        i=i+1
    cv2.imshow("wind",img)
    key=cv2.waitKey(20)
    if key==ord("c"):
        break
cv2.destroyAllWindows()
vdo.release()

In [9]:
img=cv2.imread(r"C:\Users\Dell\Desktop\New folder (2)\WD_MachineLearning-23-01-2023-\Face_detection_model\Students\Dhurv\img1.jpg",8)
cv2.imshow("window",img)
cv2.waitKey()

cv2.destroyAllWindows()

In [10]:
img.ndim

2

In [11]:
print(img)

[[ 77  64  45 ... 134 109 109]
 [ 50  73  44 ... 141 104 114]
 [ 45  52  37 ... 137 119 126]
 ...
 [ 52  52  55 ...  87  83  80]
 [ 57  57  59 ...  92  86  80]
 [ 82  82  81 ...  99  97  90]]


In [12]:
len(img.flatten())

10000

In [13]:
#conversion of image into target
X=[]
y=[]


In [14]:
import glob
address_dhurv=glob.glob(r"C:\Users\Dell\Desktop\New folder (2)\WD_MachineLearning-23-01-2023-\Face_detection_model\Students\Dhurv\*.*")


In [15]:
for i in address_dhurv:
    img=cv2.imread(i,0)
    flattern_img=img.flatten()
    X.append(flattern_img)
    y.append("Dhurv")

In [1]:
import cv2
vdo=cv2.VideoCapture(0)
Model_face=cv2.CascadeClassifier(r"trained model\haarcascade_frontalface_alt_tree.xml")
i=1
while True:
    flag,img=vdo.read()
    if flag==False:
        break
    img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=Model_face.detectMultiScale(img2)
    for x,y,w,h in face:
        cv2.rectangle(img,(x,y,w,h),(0,255,0),2)
        slice_face=img2[y:y+h,x:x+w]
        slice_face=cv2.resize(slice_face,(100,100))
        cv2.imwrite(f"Students/Gaurii/img{i}.jpg",slice_face)
        i=i+1
    cv2.imshow("wind",img)
    key=cv2.waitKey(20)
    if key==ord("c"):
        break
cv2.destroyAllWindows()
vdo.release()

In [16]:
import glob
address_gaurii=glob.glob(r"C:\Users\Dell\Desktop\New folder (2)\WD_MachineLearning-23-01-2023-\Face_detection_model\Students\Gaurii\*.*")

In [17]:
for i in address_gaurii:
    img=cv2.imread(i,0)
    flattern_img=img.flatten()
    X.append(flattern_img)
    y.append("Gaurii")

In [18]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
X_sc=sc.fit_transform(X)
print(X_sc)
from sklearn.decomposition import PCA
pca=PCA(0.99)
X_pca=pca.fit_transform(X_sc)

from sklearn.ensemble import AdaBoostClassifier
Model=AdaBoostClassifier()   # untrained model
Model.fit(X_pca,y)
Model.score(X_pca,y)

[[0.30666667 0.22068966 0.09219858 ... 0.38693467 0.3857868  0.33663366]
 [0.76       0.71724138 0.71631206 ... 0.50251256 0.43654822 0.4009901 ]
 [0.76666667 0.7862069  0.80851064 ... 0.71356784 0.81218274 0.7029703 ]
 ...
 [0.7        0.71724138 0.74468085 ... 0.01507538 0.03045685 0.02970297]
 [0.69333333 0.67586207 0.75177305 ... 0.         0.00507614 0.0049505 ]
 [0.68       0.72413793 0.75177305 ... 0.01005025 0.00507614 0.0049505 ]]


1.0

In [28]:
import cv2
vdo=cv2.VideoCapture(0)
Model_face=cv2.CascadeClassifier(r"trained model\haarcascade_frontalface_alt_tree.xml")
i=1
while True:
    flag,img=vdo.read()
    if flag==False:
        break
    img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face=Model_face.detectMultiScale(img2)
    for x,y,w,h in face:
        img2=cv2.resize(img,(100,100))
        img2=img2.flatten()
        img2=sc.transform([img2])
        img2=pca.transform(img2)
        result=Model.predict(img2)
        cv2.putText(img,text=result[0],org=(10,10),fontFace=cv2.FONT_HERSHEY_COMPLEX,color=(0,0,255),thickness=2,fontScale=1)
        cv2.rectangle(img,(x,y,w,h),(0,255,0),2)
        
    cv2.imshow("wind",img)
    key=cv2.waitKey(20)
    if key==ord("c"):
        break
cv2.destroyAllWindows()
vdo.release()

In [19]:
import cv2
import numpy as np

video=cv2.VideoCapture(0)
Model_face=cv2.CascadeClassifier("trained model/haarcascade_frontalface_alt.xml")
while True:
    flag,img=video.read()  # if img exist then flag value will be True else flag value will be false
    if flag==False:
        break

    img2=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)   #black & white img
    face=Model_face.detectMultiScale(img2)
    # cv2.putText(img,text="Press 'c' to stop",org=(10,20),fontFace=cv2.FONT_HERSHEY_COMPLEX,color=(0,0,255),thickness=2,fontScale=1)
    for x,y,w,h in face:
        cv2.rectangle(img,(x,y,w,h),(0,255,0),2)
        img3=img2[y:y+h,x:x+w]   #slice the img
        img_resize=cv2.resize(img3,dsize=(100,100))   #resize the img
        img_flatten=img_resize.flatten() 
        img_sc=sc.transform([img_flatten])
        img_pca=pca.transform(img_sc)
        result=Model.predict(img_pca)
        cv2.putText(img,text=result[0],org=(x+10,y+20),fontFace=cv2.FONT_HERSHEY_COMPLEX,color=(0,0,255),thickness=2,fontScale=1)
        result2=Model.predict_proba(img_pca)
        cv2.putText(img,text=f"{np.max(result2)}",org=(x+10,y+40),fontFace=cv2.FONT_HERSHEY_COMPLEX,color=(0,0,255),thickness=2,fontScale=1)
    cv2.imshow("wind",img)
    key=cv2.waitKey(10)
    
    if key==ord("c"):
        break
cv2.destroyAllWindows()
video.release()