In [1]:
print("Recommendation syatem")

Recommendation syatem


# Recommendation System:
> Content based ---- youtube recommendation based,


> User/Item based ---- bread+butter

# Similarity Score

Cosine similarity lies between -1 to 1

In [2]:
# Step1:  creating data on small scale first
s1="I learn java"
s2="I learn python"
s3="Virth Kohalu is cricketer"
corpus=[s1,s2,s3]

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
# Step2: Filtering data means converting data into corpus into small letters and removing stop words
tf=TfidfVectorizer(lowercase=True,stop_words='english')

In [5]:
# Step3:  sparse matrix to  dense matrix conversion
sparse_matrix=tf.fit_transform(corpus)
dense_matrix=sparse_matrix.toarray()

In [6]:
# Step4: Cosine similarity help us to get the distance between vectors using math's cos angle, where cos 90 means 0 mean not match b/w 2 vectors and cos0 means
# which mean it match 100% to each other.
# In cosine similarity, cos degree value lies between -1 to +1 where -1 is absolutely oppostive and +1 means absolutly same.
# Note: cosine similarity show similarity when degree is bigger.

from sklearn.metrics.pairwise import cosine_similarity
cs=cosine_similarity(dense_matrix)
cs

array([[1.        , 0.36644682, 0.        ],
       [0.36644682, 1.        , 0.        ],
       [0.        , 0.        , 1.        ]])

In [7]:
# Step5: Cosine distance help to find the distance b/w 2 vectors or more. If distance is higher that means not match than
       # lower that means both vectors are same.
# Note: cosine distance show similarity when distance is smaller.

from sklearn.metrics.pairwise import cosine_distances
cd=cosine_distances(dense_matrix)
cd

array([[0.        , 0.63355318, 1.        ],
       [0.63355318, 0.        , 1.        ],
       [1.        , 1.        , 0.        ]])

In [1]:
# Step6: importing pandas to read dataset of movie and clean it.

import pandas as pd
df=pd.read_csv("movies.csv")
df

movie_id                                        description  \
0     tt5286444  Neerja is the story of the courageous Neerja B...   
1     tt4434004  A story that revolves around drug abuse in the...   
2     tt0248126  Yashvardhan Raichand lives a very wealthy life...   
3     tt0347304  Naina, an introverted, perpetually depressed g...   
4     tt3043252  'Parched' is a story about women set in the he...   
...         ...                                                ...   
2845  tt0308793                                                NaN   
2846  tt3006508                                                NaN   
2847  tt5348692  The plot is simple. Ranganna (Rangayana Raghu)...   
2848  tt3171754                                                NaN   
2849  tt0231455                                                NaN   

                                        language                  released  \
0                                    [ "Hindi" ]  2016-02-19T00:00:00.000Z   
1                         [ "Hindi", "Panjabi" ]  2016-06-17T00:00:00.000Z   
2                 [ "Hindi", "English", "Urdu" ]  2001-12-14T00:00:00.000Z   
3     [ "Hindi", "Urdu", "Gujarati", "Panjabi" ]  2003-11-28T00:00:00.000Z   
4                         [ "Hindi", "English" ]  2016-06-17T00:00:00.000Z   
...                                          ...                       ...   
2845                               [ "Kannada" ]                       NaN   
2846                               [ "Kannada" ]                2013-02-22   
2847                               [ "Kannada" ]                2013-11-29   
2848                               [ "Kannada" ]                2013-12-27   
2849                               [ "Kannada" ]                       NaN   

      rating                                          writer  \
0        7.9  [ "Saiwyn Quadras", "Sanyukta Shaikh Chawla" ]   
1        7.9          [ "Sudip Sharma", "Abhishek Chaubey" ]   
2        7.5              [ "Karan Johar", "Sheena Parikh" ]   
3        8.0           [ "Niranjan Iyengar", "Karan Johar" ]   
4        7.6               [ "Supratik Sen", "Leena Yadav" ]   
...      ...                                             ...   
2845     7.7                                              []   
2846     7.7                                              []   
2847     7.7                                [ "Pc Shekhar" ]   
2848     7.6                                              []   
2849     7.5                                              []   

                        director  \
0             [ "Ram Madhvani" ]   
1         [ "Abhishek Chaubey" ]   
2              [ "Karan Johar" ]   
3           [ "Nikkhil Advani" ]   
4              [ "Leena Yadav" ]   
...                          ...   
2845       [ "V. Ravichandran" ]   
2846            [ "Nagashekar" ]   
2847            [ "Pc Shekhar" ]   
2848          [ "Manju Swaraj" ]   
2849  [ "S.R. Puttana Kanagal" ]   

                                                   cast  \
0     [ "Sonam Kapoor", "Shabana Azmi", "Yogendra Ti...   
1     [ "Alia Bhatt", "Shahid Kapoor", "Diljit Dosan...   
2     [ "Amitabh Bachchan", "Jaya Bhaduri", "Shah Ru...   
3     [ "Shah Rukh Khan", "Preity Zinta", "Saif Ali ...   
4     [ "Tannishtha Chatterjee", "Radhika Apte", "Le...   
...                                                 ...   
2845  [ "V. Ravichandran", "Kushboo", "Anant Nag", "...   
2846  [ "Chethan Kumar", "Nithya Menon", "Sarath Kum...   
2847   [ "Rangayana Raghu", "Sadhu Kokila", "Avinash" ]   
2848  [ "Ganesh", "Amulya", "Anant Nag", "Tara", "Av...   
2849                                                 []   

                                     genre                         name  
0     [ "Biography", "Drama", "Thriller" ]                       Neerja  
1         [ "Crime", "Drama", "Thriller" ]                  Udta Punjab  
2        [ "Drama", "Musical", "Romance" ]  Kabhi Khushi Kabhie Gham...  
3         [ "Comedy", 

In [2]:
# Step7: Filtering columns which is required
df1=df.iloc[:,[1,-1]]

In [11]:
df1=df.dropna()
df1

movie_id                                        description  \
0     tt5286444  Neerja is the story of the courageous Neerja B...   
1     tt4434004  A story that revolves around drug abuse in the...   
2     tt0248126  Yashvardhan Raichand lives a very wealthy life...   
3     tt0347304  Naina, an introverted, perpetually depressed g...   
4     tt3043252  'Parched' is a story about women set in the he...   
...         ...                                                ...   
2838  tt5872120  Antony is depressed and wants to commit suicid...   
2841  tt3666724  A bubbly tale, the story is about four pairs o...   
2842  tt5652478  The film tells the story of Sodabuddi, who spe...   
2844  tt5508936  Vamshi, under the eye of his mother is living ...   
2847  tt5348692  The plot is simple. Ranganna (Rangayana Raghu)...   

                                        language                  released  \
0                                    [ "Hindi" ]  2016-02-19T00:00:00.000Z   
1                         [ "Hindi", "Panjabi" ]  2016-06-17T00:00:00.000Z   
2                 [ "Hindi", "English", "Urdu" ]  2001-12-14T00:00:00.000Z   
3     [ "Hindi", "Urdu", "Gujarati", "Panjabi" ]  2003-11-28T00:00:00.000Z   
4                         [ "Hindi", "English" ]  2016-06-17T00:00:00.000Z   
...                                          ...                       ...   
2838                               [ "Kannada" ]                2016-07-08   
2841                               [ "Kannada" ]                2009-01-23   
2842                               [ "Kannada" ]                2016-04-15   
2844                               [ "Kannada" ]                2008-10-02   
2847                               [ "Kannada" ]                2013-11-29   

      rating                                          writer  \
0        7.9  [ "Saiwyn Quadras", "Sanyukta Shaikh Chawla" ]   
1        7.9          [ "Sudip Sharma", "Abhishek Chaubey" ]   
2        7.5              [ "Karan Johar", "Sheena Parikh" ]   
3        8.0           [ "Niranjan Iyengar", "Karan Johar" ]   
4        7.6               [ "Supratik Sen", "Leena Yadav" ]   
...      ...                                             ...   
2838     7.7            [ "Raghu Shastry", "Raghu Shastry" ]   
2841     7.7              [ "Sekhar Kammula", "B.A. Madhu" ]   
2842     7.7      [ "Jyothirao Mohith", "Jyothirao Mohith" ]   
2844     7.7                                   [ "Prakash" ]   
2847     7.7                                [ "Pc Shekhar" ]   

                    director  \
0         [ "Ram Madhvani" ]   
1     [ "Abhishek Chaubey" ]   
2          [ "Karan Johar" ]   
3       [ "Nikkhil Advani" ]   
4          [ "Leena Yadav" ]   
...                      ...   
2838     [ "Raghu Shastry" ]   
2841      [ "M.D. Sridhar" ]   
2842  [ "Jyothirao Mohith" ]   
2844           [ "Prakash" ]   
2847        [ "Pc Shekhar" ]   

                                                   cast  \
0     [ "Sonam Kapoor", "Shabana Azmi", "Yogendra Ti...   
1     [ "Alia Bhatt", "Shahid Kapoor", "Diljit Dosan...   
2     [ "Amitabh Bachchan", "Jaya Bhaduri", "Shah Ru...   
3     [ "Shah Rukh Khan", "Preity Zinta", "Saif Ali ...   
4     [ "Tannishtha Chatterjee", "Radhika Apte", "Le...   
...                                                 ...   
2838  [ "Vinay Rajkumar", "Ruksar Meer", "Sushmitha ...   
2841              [ "Pradeep Bogadi", "Aishwarya Nag" ]   
2842  [ "Uthpal", "Anusha", "Khushi", "Rangayana Rag...   
2844  [ "Puneeth Rajkumar", "Nikita Thukral", "Laksh...   
2847   [ "Rangayana Raghu", "Sadhu Kokila", "Avinash" ]   

                                     genre                          name  
0     [ "Biography", "Drama", "Thriller" ]                        Neerja  
1         [ "Crime", "Drama", "Thriller" ]                   Udta Punjab  
2        [ "Drama", "Musical", "Romance" ]   Kabhi Khushi Kabhie Gham...  
3         [ "Comedy", "Drama", "Romance" ]                 Kal Ho 

In [12]:
df.shape

(2850, 10)

In [3]:
df2=df1.dropna()

In [4]:
df2.shape

(1752, 2)

In [19]:
df2

description  \
0     Neerja is the story of the courageous Neerja B...   
1     A story that revolves around drug abuse in the...   
2     Yashvardhan Raichand lives a very wealthy life...   
3     Naina, an introverted, perpetually depressed g...   
4     'Parched' is a story about women set in the he...   
...                                                 ...   
2838  Antony is depressed and wants to commit suicid...   
2841  A bubbly tale, the story is about four pairs o...   
2842  The film tells the story of Sodabuddi, who spe...   
2844  Vamshi, under the eye of his mother is living ...   
2847  The plot is simple. Ranganna (Rangayana Raghu)...   

                              name  
0                           Neerja  
1                      Udta Punjab  
2      Kabhi Khushi Kabhie Gham...  
3                    Kal Ho Naa Ho  
4                          Parched  
...                            ...  
2838                    Run Antony  
2841                    Jolly Days  
2842  The Great Story of Sodabuddi  
2844                        Vamshi  
2847                  Chaddi Dosth  

[1752 rows x 2 columns]

In [5]:
import numpy as np

corpus3=np.array(df2.iloc[:,0])
corpus3

array(['Neerja is the story of the courageous Neerja Bhanot, who sacrificed her life while protecting the lives of 359 passengers on the Pan Am flight 73 in 1986. The flight was hijacked by a terrorist organization.',
       'A story that revolves around drug abuse in the affluent north Indian State of Punjab and how the youth there have succumbed to it en-masse resulting in a socio-economic decline.',
       'Yashvardhan Raichand lives a very wealthy lifestyle along with his wife, Nandini, and two sons, Rahul and Rohan. While Rahul has been adopted, Yashvardhan and Nandini treat him as their own...',
       ...,
       'The film tells the story of Sodabuddi, who spends his life wastefully. He has two romantic encounters and the audience gets to relive these tales, until the climax throws in a complete surprise.',
       'Vamshi, under the eye of his mother is living in an ordinary house is given all care to become a police man. The rejected mother the dejected son wants to carve a fre

In [21]:
# Step9:  conversion of description of movies of dataframe into corpus using pandas df1.description.
# Step10: TfidVectorizer and countvectorizer both use for creating feature from corpus nd also contain corpus preprocessing.
# Step11:  Creating dense matrix from sparse matrix with the help of toarray() method.

In [6]:
import re
corpus4=[]
for i in corpus3:
    corpus4.append(re.sub("[^a-z]","",i.lower()))
corpus4

['neerjaisthestoryofthecourageousneerjabhanotwhosacrificedherlifewhileprotectingthelivesofpassengersonthepanamflightintheflightwashijackedbyaterroristorganization',
 'astorythatrevolvesarounddrugabuseintheaffluentnorthindianstateofpunjabandhowtheyouththerehavesuccumbedtoitenmasseresultinginasocioeconomicdecline',
 'yashvardhanraichandlivesaverywealthylifestylealongwithhiswifenandiniandtwosonsrahulandrohanwhilerahulhasbeenadoptedyashvardhanandnandinitreathimastheirown',
 'nainaanintrovertedperpetuallydepressedgirlslifechangeswhenshemeetsamanbutamanhasasecretofhisownwhichchangestheirlivesforeverembroiledinallthisisrohitnainasbestfriendwhoconcealshisloveforher',
 'parchedisastoryaboutwomensetintheheartofparchedrurallandscapeofrajasthanindiaittracesthebittersweettaleoffourordinarywomenranilajjobijliandjanakiwesee',
 'theclassicstoryofaterminallyillmanwhowishestolivelifetothefullbeforetheinevitableoccursastoldbyhisbestfriend',
 'astrangerinthecityasksquestionsnoonehasaskedbeforeknownonlybyh

In [7]:
from nltk.corpus import stopwords

sw=stopwords.words("english")
sw.remove("not")

In [8]:
len(sw)

178

In [25]:
for i in sw:
    if "not" == i:
        print(True)

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer(stop_words=sw)
dense_matrix=tf.fit_transform(corpus4).toarray()

In [10]:
# Step12:  importing algo for recommendation which is nearestneighbours it partically work like knn(knn doesnot have cosine: codine_similarity and cosine_distance)

# Most import NearestNeighbours is for "unsupervised learning" where target is not required

from sklearn.neighbors import NearestNeighbors
model=NearestNeighbors()             #bydefault it calculate equilidian distance.
model.fit(dense_matrix)

NearestNeighbors()

In [33]:
model.kneighbors([dense_matrix[0]],n_neighbors=4)     # yha predict ni hota neighbours puchte h

(array([[0.        , 1.41421356, 1.41421356, 1.41421356]]),
 array([[0, 1, 2, 3]], dtype=int64))

In [34]:
name=[i.lower() for i in list(df2.name)]
file=input("Enter film name:")
index_film=name.index(file)

similarity_score,film_list=model.kneighbors([dense_matrix[index_film]],n_neighbors=5)

for i in film_list[0][1:]:
    print(name[i])

kabhi khushi kabhie gham...
neerja
kal ho naa ho
parched
