# NLP:Natural Processing Language

In [2]:
# pip install nltk

     ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
      --------------------------------------- 0.0/1.5 MB 325.1 kB/s eta 0:00:05
      --------------------------------------- 0.0/1.5 MB 325.1 kB/s eta 0:00:05
      --------------------------------------- 0.0/1.5 MB 325.1 kB/s eta 0:00:05
      --------------------------------------- 0.0/1.5 MB 325.1 kB/s eta 0:00:05
     - -------------------------------------- 0.0/1.5 MB 140.3 kB/s eta 0:00:11
     -- ------------------------------------- 0.1/1.5 MB 255.1 kB/s eta 0:00:06
     -- ------------------------------------- 0.1/1.5 MB 261.7 kB/s eta 0:00:06
     -- ------------------------------------- 0.1/1.5 MB 261.7 kB/s eta 0:00:06
     -- ------------------------------------- 0.1/1.5 MB 261.7 kB/s eta 0:00:06
     --- ------------------------------------ 0.1/1.5 MB 240.2 kB/s eta 0:00:06
     ---- ----------------------------------- 0.2/1.5 MB 2


[notice] A new release of pip is available: 23.0 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import nltk

In [3]:
# nltk.download()

In [4]:
review1="food is good and food is tasty"     #document
review2="foo8889d is!$ not tasty"
review3="cheap quality&&&&"
review4="expensive** stuff#"
review5="Food is aweso0me^^"


corpus=[review1,review2,review3,review4,review5] # corpus is not feature
target=[1,0,0,0,1]
corpus

['food is good and food is tasty',
 'foo8889d is!$ not tasty',
 'cheap quality&&&&',
 'expensive** stuff#',
 'Food is aweso0me^^']

In [5]:
def punctuation_remover(corpus):
    corpus1=[]
    for i in corpus:
         jhanvi=""
         for j in i:
             if j not in "1234567890!#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~":
                jhanvi+=j

         corpus1.append(jhanvi.lower()) 
    return corpus1

In [6]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [7]:
from nltk.corpus import stopwords
len(stopwords.words("english"))
sw=stopwords.words("english")
sw.remove("not")
sw.remove("no")

In [8]:
def stopword_remover(corpus1):
    corpus2=[]
    for i in corpus1:
        split_word=i.split()
        new_str=""
        for j in split_word:
            if j not in sw:
                new_str=new_str+j+" "
        result=corpus2.append(new_str.strip())
    return corpus2

In [9]:
#import re                                  #another method
#reviews1="this!!!! i@s jhanvi2501"
#re.sub("[^a-z ]","",reviews1)
#corpus
#for i in corpus:                              # time complexity is less
#   print(re.sub("[^a-z ]","",i))


In [10]:
print(corpus)
def cleaner(corpus):
     result=punctuation_remover(corpus)
     clean_corpus=stopword_remover(result)
     return clean_corpus
corpus1=cleaner(corpus)
corpus1



['food is good and food is tasty', 'foo8889d is!$ not tasty', 'cheap quality&&&&', 'expensive** stuff#', 'Food is aweso0me^^']


['food good food tasty',
 'food not tasty',
 'cheap quality',
 'expensive stuff',
 'food awesome']

vectoriz:  conversion of string into array after tokenizing.
> Countvectorizer.

> tfidvectorizer.

In [11]:
# creating feature using countvectorizer
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
cv.fit_transform(corpus1)

<5x9 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [12]:
print(cv.fit_transform(corpus1))
print(cv.fit_transform(corpus1).toarray())      #dense matrix
print("all feature name :",cv.get_feature_names_out())

  (0, 3)	2
  (0, 4)	1
  (0, 8)	1
  (1, 3)	1
  (1, 8)	1
  (1, 5)	1
  (2, 1)	1
  (2, 6)	1
  (3, 2)	1
  (3, 7)	1
  (4, 3)	1
  (4, 0)	1
[[0 0 0 2 1 0 0 0 1]
 [0 0 0 1 0 1 0 0 1]
 [0 1 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 1 0 0 0 0 0]]
all feature name : ['awesome' 'cheap' 'expensive' 'food' 'good' 'not' 'quality' 'stuff'
 'tasty']


In [13]:
X=cv.fit_transform(corpus1).toarray()  #feature
X

array([[0, 0, 0, 2, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 0]], dtype=int64)

In [14]:
target

[1, 0, 0, 0, 1]

In [15]:
#Training Model2
from sklearn.linear_model import LogisticRegression
Model1=LogisticRegression(max_iter=2000)
Model1.fit(X,target)
Model1.score(X,target)

1.0

In [16]:
#Testing our model
sample_review=["food is not so tasty"]
sample=cleaner(sample_review)
sample

['food not tasty']

In [17]:
cv.transform(sample)

<1x9 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [18]:
sample_feature=cv.transform(sample).toarray()
sample_feature

array([[0, 0, 0, 1, 0, 1, 0, 0, 1]], dtype=int64)

In [19]:
Model1.predict(sample_feature)

array([0])

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(1,2))
sparse_matrix=cv.fit_transform(corpus1)
X=sparse_matrix.toarray()
print(X)
print(cv.get_feature_names_out())

[[0 0 0 0 0 2 0 1 0 1 1 1 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 1]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0]]
['awesome' 'cheap' 'cheap quality' 'expensive' 'expensive stuff' 'food'
 'food awesome' 'food good' 'food not' 'food tasty' 'good' 'good food'
 'not' 'not tasty' 'quality' 'stuff' 'tasty']


In [21]:
# TfidfVectorizer--> tf-term frequency, i= inverse, df=document frequency, Vectore = 1D array
corpus1

['food good food tasty',
 'food not tasty',
 'cheap quality',
 'expensive stuff',
 'food awesome']

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer(ngram_range=(1,2))
tf.fit_transform(corpus1)
print(tf.fit_transform(corpus1))    #sparse matrix
X=tf.fit_transform(corpus1).toarray()   # dense matrix
print("all feature name :",tf.get_feature_names_out())

  (0, 9)	0.3939032102412759
  (0, 11)	0.3939032102412759
  (0, 7)	0.3939032102412759
  (0, 16)	0.31779862980636625
  (0, 10)	0.3939032102412759
  (0, 5)	0.5276031413284658
  (1, 13)	0.493899144769786
  (1, 8)	0.493899144769786
  (1, 12)	0.493899144769786
  (1, 16)	0.3984747201583652
  (1, 5)	0.3307700134258465
  (2, 2)	0.5773502691896258
  (2, 14)	0.5773502691896258
  (2, 1)	0.5773502691896258
  (3, 4)	0.5773502691896258
  (3, 15)	0.5773502691896258
  (3, 3)	0.5773502691896258
  (4, 6)	0.6390704413963749
  (4, 0)	0.6390704413963749
  (4, 5)	0.42799292268317357
all feature name : ['awesome' 'cheap' 'cheap quality' 'expensive' 'expensive stuff' 'food'
 'food awesome' 'food good' 'food not' 'food tasty' 'good' 'good food'
 'not' 'not tasty' 'quality' 'stuff' 'tasty']


In [23]:
# Resturant_review import and train NLP model

import pandas as pd

df=pd.read_csv(r"Restaurant_Reviews.tsv",delimiter="\t")
df

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [24]:
corpus_review=df["Review"].values
corpus_review

array(['Wow... Loved this place.', 'Crust is not good.',
       'Not tasty and the texture was just nasty.',
       'Stopped by during the late May bank holiday off Rick Steve recommendation and loved it.',
       'The selection on the menu was great and so were the prices.',
       'Now I am getting angry and I want my damn pho.',
       "Honeslty it didn't taste THAT fresh.)",
       'The potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer.',
       'The fries were great too.', 'A great touch.',
       'Service was very prompt.', 'Would not go back.',
       'The cashier had no care what so ever on what I had to say it still ended up being wayyy overpriced.',
       'I tried the Cape Cod ravoli, chicken, with cranberry...mmmm!',
       'I was disgusted because I was pretty sure that was human hair.',
       'I was shocked because no signs indicate cash only.',
       'Highly recommended.', 'Waitress was a little slow in service.'

In [25]:
coprus_review_cleaned=cleaner(corpus_review)
coprus_review_cleaned    

['wow loved place',
 'crust not good',
 'not tasty texture nasty',
 'stopped late may bank holiday rick steve recommendation loved',
 'selection menu great prices',
 'getting angry want damn pho',
 'honeslty didnt taste fresh',
 'potatoes like rubber could tell made ahead time kept warmer',
 'fries great',
 'great touch',
 'service prompt',
 'would not go back',
 'cashier no care ever say still ended wayyy overpriced',
 'tried cape cod ravoli chicken cranberrymmmm',
 'disgusted pretty sure human hair',
 'shocked no signs indicate cash',
 'highly recommended',
 'waitress little slow service',
 'place not worth time let alone vegas',
 'not like',
 'burrittos blah',
 'food amazing',
 'service also cute',
 'could care less interior beautiful',
 'performed',
 'thats rightthe red velvet cakeohhh stuff good',
 'never brought salad asked',
 'hole wall great mexican street tacos friendly staff',
 'took hour get food tables restaurant food luke warm sever running around like totally overwhelmed'

In [26]:
y=df["Liked"].values
y

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,

 BernoulliNB --> binary class(when we have two class in the target )  //

 CountVectorizer  --> 0 class ->0.96

#GaussianNB--> binary class(when we have two class in the target ) // 

TfidfVectorizer

MultinomialNB --> dataset target must be more then 2 


 Note: do you own experiment

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf=TfidfVectorizer(ngram_range=(1,2))     # ngram increases the feature

sparse_metric=tf.fit_transform(coprus_review_cleaned)
X=sparse_metric.toarray()
len(tf.get_feature_names_out())
from sklearn.naive_bayes import BernoulliNB
Model2=BernoulliNB()
Model2.fit(X,y)

sample2=["foo3252545d quali35435ty is 66546not so good"]
sample3=cleaner(sample2)
print(sample3)
sample4=tf.transform(sample3).toarray()
print(sample4)
print(Model2.predict(sample4))
Model2.predict_proba(sample4)

['food quality not good']
[[0. 0. 0. ... 0. 0. 0.]]
[0]


array([[0.96744331, 0.03255669]])

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf=TfidfVectorizer(ngram_range=(1,2))

sparse_metric=tf.fit_transform(coprus_review_cleaned)
X=sparse_metric.toarray()
len(tf.get_feature_names_out())
from sklearn.naive_bayes import GaussianNB
Model2=GaussianNB()
Model2.fit(X,y)

sample2=["foo3252545d quali35435ty is 66546not so good"]
sample3=cleaner(sample2)
print(sample3)
sample4=tf.transform(sample3).toarray()
print(sample4)
print(Model2.predict(sample4))
Model2.predict_proba(sample4)

['food quality not good']
[[0. 0. 0. ... 0. 0. 0.]]
[0]


array([[1., 0.]])

In [29]:
from sklearn.feature_extraction.text import CountVectorizer

tf=CountVectorizer(ngram_range=(1,2))

sparse_metric=tf.fit_transform(coprus_review_cleaned)
X=sparse_metric.toarray()
len(tf.get_feature_names_out())
from sklearn.naive_bayes import BernoulliNB
Model2=BernoulliNB()
Model2.fit(X,y)

sample2=["foo3252545d quali35435ty is 66546not so good"]
sample3=cleaner(sample2)
print(sample3)
sample4=tf.transform(sample3).toarray()
print(sample4)
print(Model2.predict(sample4))
Model2.predict_proba(sample4)

['food quality not good']
[[0 0 0 ... 0 0 0]]
[0]


array([[0.96744331, 0.03255669]])

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

tf=CountVectorizer(ngram_range=(1,2))

sparse_metric=tf.fit_transform(coprus_review_cleaned)
X=sparse_metric.toarray()
len(tf.get_feature_names_out())
from sklearn.naive_bayes import BernoulliNB
Model2=GaussianNB()
Model2.fit(X,y)

sample2=["foo3252545d quali35435ty is 66546not so good"]
sample3=cleaner(sample2)
print(sample3)
sample4=tf.transform(sample3).toarray()
print(sample4)
print(Model2.predict(sample4))
Model2.predict_proba(sample4)

['food quality not good']
[[0 0 0 ... 0 0 0]]
[0]


array([[1., 0.]])

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

tf=CountVectorizer()

sparse_metric=tf.fit_transform(coprus_review_cleaned)
X=sparse_metric.toarray()
len(tf.get_feature_names_out())
from sklearn.naive_bayes import BernoulliNB
Model2=BernoulliNB()
Model2.fit(X,y)

sample2=["foo3252545d quali35435ty is 66546not so good"]
sample3=cleaner(sample2)
print(sample3)
sample4=tf.transform(sample3).toarray()
print(sample4)
print(Model2.predict(sample4))
Model2.predict_proba(sample4)

['food quality not good']
[[0 0 0 ... 0 0 0]]
[0]


array([[0.58560075, 0.41439925]])

In [32]:

from sklearn.feature_extraction.text import TfidfVectorizer

tf=TfidfVectorizer()

sparse_metric=tf.fit_transform(coprus_review_cleaned)
X=sparse_metric.toarray()
len(tf.get_feature_names_out())
from sklearn.naive_bayes import BernoulliNB
Model2=BernoulliNB()
Model2.fit(X,y)

sample2=["foo3252545d quali35435ty is 66546not so good"]
sample3=cleaner(sample2)
print(sample3)
sample4=tf.transform(sample3).toarray()
print(sample4)
print(Model2.predict(sample4))
Model2.predict_proba(sample4)

['food quality not good']
[[0. 0. 0. ... 0. 0. 0.]]
[0]


array([[0.58560075, 0.41439925]])